apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-web-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: rook-cephfs
  volumeMode: Filesystem