apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-web-data
  namespace: kmgetubs19
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  volumeMode: Filesystem
