apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-web-data
  namespace: kmgetubs19
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  storageClassName: openebs-zfspv
  volumeMode: Filesystem