apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-db-data
  namespace: kmgetubs19
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem