apiVersion: v1
kind: Service
metadata:
  labels:
    app: odoo11
    component: postgres
  name: db
  namespace: kmgetubs19
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: odoo11
    component: postgres