kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  labels:
    app: odoo11
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo11
      component: postgres
  template:
    metadata:
      labels:
        app: odoo11
        component: postgres
    spec:
      volumes:
        - name: odoo-db-data
          persistentVolumeClaim:
            claimName: odoo-db-data
        - name: postgres-config
          configMap:
            name: postgres-config
      containers:
        - resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  psql -h 127.0.0.1 -U $POSTGRES_USER -q -d $POSTGRES_USER -c 'SELECT
                  1'
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          name: postgres
          env:
            - name: PGDATA
              value: /var/lib/pgsql/data
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: odoo
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: odoo-db-data
              mountPath: /var/lib/pgsql/
            - name: postgres-config
              mountPath: /docker-entrypoint-initdb.d/  

          terminationMessagePolicy: File
          image: postgres:9.4-alpine
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
