{{ range .Values.routes }}
    {{- $servicename := .name -}}
    {{- $resolver := .dns_resolver -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-route-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    {{ range .domains }}
    - match: Host(`{{ trimPrefix "https://" .domain }}`)
      kind: Rule
      priority: 5 
      services:
      - kind: Service
        name: svc-{{ $servicename }}
      #middlewares:
      #- name: secure
      #  namespace: traefik
      #- name: app-passthrough-{{ .name }}-header
      tls:
        certResolver: {{ $resolver }}
    {{ end }}
 {{ range .domains }}    
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mw-forwarded-for-{{ .domain }}-header
spec:
  headers:
    customRequestHeaders:
      Forwarded: for=unknown;host={{ .domain }};proto=https
{{ end }}      
---
kind: Service
apiVersion: v1
metadata:
  name: svc-{{ $servicename }}
spec:
  type: ExternalName
  externalName: {{ .host }}
  ports:
    - port: {{ .port }}
{{ end }}

