storj-s3-gateway:
  replicaCount: 2
  image:
    repository: storjlabs/gateway
    tag: latest
  args: [ "run" ]
  network:
    http:
      servicePort: 7777
  service:
    type: NodePort        
  resources:
    requests:
      memory: 10Gi
    limits:
      memory: 10Gi
      cpu: 4.0
  defaultAffinityRules:
    enabled: false
  persistence:
    enabled: true
    storageClass: openebs-zfspv
    accessModes: ReadWriteOnce
    name: storj-data
    size: 1Gi
    annotations:
      pv.kubernetes.io/bound-by-controller: 'yes'
  volumeMounts:
  - mountPath: /root/.local/share/storj/gateway/
    name: storj-config
  - mountPath: /root/.local/share/storj/gateway/minio/
    name: storj-data
  volumes:
  - name: storj-config
    secret:
      secretName: storj-config
