apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: openebs-zfslocalpw
    namespace: argocd

spec:
    destination:
        namespace: openebs
        server: https://kubernetes.default.svc
    project: default
    source:
        path: openebs
        targetRevision: HEAD
        helm:
            valueFiles:
                - values.yaml
        repoURL: https://github.com/luechtdiode/mk8-argo.git
    syncPolicy:
        automated:
            prune: true
        syncOptions:
          - CreateNamespace=true

