{{ range .Values.routes }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-passthrough-{{ .name }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ trimPrefix "http://" .domain }}`)
      kind: Rule
      priority: 5
      services:
        - kind: Service
          {{- if .host }}
          name: app-passthrough-{{ .name }}
          {{- end}}
          {{- if not .host }}
          name: {{ .name }}
          {{- end }}
          port: {{ .port }}
      middlewares:
      - name: standard
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-passthrough-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ trimPrefix "https://" .domain }}`)
      kind: Rule
      priority: 5 
      services:
      - kind: Service
        {{- if .host }}
        name: app-passthrough-{{ .name }}
        {{- end}}
        {{- if not .host }}
        name: {{ .name }}
        {{- end }}
        port: {{ .portSecure }}
      middlewares:
      - name: standard
      tls:
        certResolver: {{ .dns_resolver }}
{{- if .host }}
---
kind: Service
apiVersion: v1
metadata:
  name: app-passthrough-{{ .name }}
spec:
  type: ExternalName
  externalName: {{ .host }}
{{- end }}  
{{ end }}

