apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kutu-data
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: microk8s.io/hostpath    
  finalizers:
    - kubernetes.io/pvc-protection  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem