kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-config
  namespace: kutuapp-test

data:
  init.sql: |-
    CREATE ROLE kutu_admin WITH SUPERUSER USER kutuadmin;
    CREATE SCHEMA IF NOT EXISTS kutu AUTHORIZATION kutu_admin;
    SET search_path TO kutu;
