apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-kutuapp-test2
  namespace: kutuapp-test
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - kutuapp-test
  selector:
    matchLabels:
      app: kutuapp