apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-kutuapp-test
  namespace: kutuapp-test
spec:
  # jobLabel: app
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: kutuapp
  namespaceSelector:
    matchNames:
      - kutuapp-test