apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-grafana-secret
  namespace: prometheus
spec:
  encryptedData:
    admin-password: AgA+pztvlglsmsvK5QyqI88gRYi2LwNs1gtf6iCQV7u1TFpk3nF49rXowedK2UzBiEmSpy9+W7CJOSOhUHRP38taPgTTXYBkcMHhzcxWtEhFKU3a50KkJTkLmgEe2FZO42mGBObwLOkLssonDfUXlAG4KUStn6Dnlckh4W26kiujltgcTuiB13Jeyj1UOG9FZL4btKGzrWabjZTYYIMD7tvqpNnTgY04PrKC5/dN19amldAAF2WzLj2nDsfd+Jf6mi23gbdNGOYOdbnFFD9q1SOmprzGd04JDRUvd+N5GARP3QIG/7SKAs2SSFtfiqTQZMHrFTNC9d1iRSmizFiQRZoQ8buqaMzQqN9Uea63RTyZtQ6ZmlQFf1/XDPDOZ+K+8RXVpNNNTp3vOBfBg2MS5SnwG5RihdYE+S0HyiHIAZKz7O3YdSj1KPUH2qjmPNMZTNxdTDOuqvo01eytLE6qjZvGBZSkgJ9fEdL070s5AHJsCXP+BkAnDtSFBo4uQO+Lw+9XTDYf4qedCcRjVUIEcWqY3tHj8HpGrEbipcyYy6fn1hKvvmcVbvfD4md3dS2xi6CL9swGegu75TCQIueyUYQdbMKgv4wBpr1yRoA/+Jp6S3ONr21qeJ+y33wm9M9/2a1BEaZ0qbdiJB1osL4Y3SZRxTvlml4dJbyecqpsWaNJf9ausEEt72N7sgVaV2762roecUdf7A==
    admin-user: AgATZg9zR99nkdcClaawpP0ynS7U+hnp37FEFlu0+alKWVoDjqCIpFD+eI4eITEtQQrzaIL3FpEs91PqKFA+kvkFU8xaWDEy6K3QOt+3b49jC0vNchjH75oJkwmurAYc7ke4Tl0NMhfTxfy8U8MpB8E3YNMaQdve5tO+Wg8fJgRgi+8sFx65p3lgQJbIQdxcq5d1VtEykG3csQQdrBBPVCbattjeuqxx0o1qfPFrYFChQUEbs0kZ0eSlqEuwkwgEGfM9NTbROeD7U4W85Xr9oIOU7+WHrif7b6tMexNgxHlqcUjXyAkbsCq/GS8K0lhRjEMCa1sq3sFE7IFy5SM83Fg8NavqNhxOietn31w3aRyKyqKxlkegysCIJzM4P9cHwzithGmiSV058si/uiknqfmN3mV62wip+e5GddHhU8n9FLiqdq3PiujFsghq6YzIPSLSPIRrrrWy2sGCKXXnlzU7WVGNxXvuf/2D5gs8DW2spHmUKsct7mpHwGfdLkcA+f5NvFkheX4rT175vj7+mkaAULgIMkX8CmWr9jMt7P1KvI/fC1J3SHwknZTBzgta0o8lXyGJXwvK0zhT1bNLElhYWykHWJQmLwL/k/yQo53bzX45rm3wkcIWBURqAGf7JJUprsetix4wLkWOJpwSkcnIFl+HCBJubfJ6XqB1UKu4/hm/ccEUu8H39rMvEUliVYxLcJePW7/Tq36mjw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: prometheus-grafana-secret
      namespace: prometheus

