kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: 'false'
  dex.config: |
    connectors:
      # GitHub
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Iv1.696e329182673296
          clientSecret: $dex.github.clientSecret
  repositories: |
    - type: git
      url: https://github.com/luechtdiode/mk8-argo.git
  url: 'https://argo.interpolar.ch:8443'
