kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, luechtdiode, role:admin
  policy.default: 'role:readonly'
  scopes: '[preferred_username, groups, email]'
