{{- if .Values.templates.argo_uri }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingress-route
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{- .Values.templates.argo_uri }}`)
      priority: 10
      services:
        - name: argocd-server
          port: 443
      middlewares:
      - name: security-response-header
        namespace: traefik
      - name: more-security-response-header
        namespace: traefik
      tls:
        certResolver: cf-production
    - kind: Rule
      match: Host(`{{- .Values.templates.argo_uri }}`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 443
          scheme: h2c
      middlewares:
      - name: security-response-header
        namespace: traefik
      - name: more-security-response-header
        namespace: traefik
      tls:
        certResolver: Host(`{{- .Values.templates.certResolver }}`)
{{- end }}
