kind: Deployment
apiVersion: apps/v1
metadata:
  name: argocd-dex-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: dex
          envFrom:
            - secretRef:
                name: dex-argo-github-secret
