apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kmgetubs19
    namespace: argocd
spec:
    destination:
        namespace: kmgetubs19
        server: https://kubernetes.default.svc
    project: default
    source:
        path: kmgetubs19
        targetRevision: HEAD
        helm:
            valueFiles:
                - values.yaml
        repoURL: https://github.com/luechtdiode/mk8-argo.git
    syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
