routes:
  - name: idp-waf
    domain: keycloak.interpolar.ch
    dns_resolver: "cf-production"
    port: 8069
    portSecure: 8069

idp-waf:
  replicaCount: 1
  image:
    repository: luechtdiode/nginx-naxsi
    tag: master-1df1bb5
  network:
    http:
      containerPort: 8080
      servicePort: 8069
  service:
    type: NodePort
  resources:
    requests:
      cpu: 0.5
      memory: 128Mi
    limits:
      cpu: 1.00
      memory: 512Mi
  volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-cm

idp:
  global:
    storageClass: openebs-hostpath
  service:
    type: NodePort
  serviceMonitor:
    enabled: true
    namespace: "monitoring"