apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: sealed-secrets-controller
    namespace: sealed-secrets

spec:
    destination:
        namespace: sealed-secrets
        server: https://kubernetes.default.svc
    project: default
    source:
        path: sealed-secrets
        targetRevision: HEAD
        helm:
            valueFiles:
                - values.yaml
        repoURL: https://github.com/luechtdiode/mk8-argo.git
    syncPolicy:
        automated:
            prune: true
        syncOptions:
          - CreateNamespace=true

