routes:
  - name: sharevic
    domains:
       - domain: sharevic.net
       - domain: www.sharevic.net
       - domain: interpolar.ch
       - domain: www.interpolar.ch
    host: pluto.fritz.box
    port: 443
    dns_resolver: "cf-production"
