routes:
  - name: kutuapp
    domain: kutuapp.sharevic.net
    dns_resolver: "cf-production"
    port: 5757
    portSecure: 5757

kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: v2r2b21
  network:
    metrics:
      servicePort: 3000
      targetPort: http
    http:
      servicePort: 5757
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 0.50
      memory: 1.5Gi
    limits:
      cpu: 3.00
      memory: 2.0Gi
  livenessProbe:
    httpGet:
      path: /metrics
      port: 5757
  readynessProbe:
    httpGet:
      path: /
      port: 5757
  envFrom:
    - secretRef:
        name: smtp-secret
  env:
    - name: X_KUTU_SECRET
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: kutusecret
    - name: X_DB_CONFIG_NAME
      value: kutudb_pg
    - name: X_POSTGRES_HOST
      value: postgres
    - name: X_POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: user      
    - name: X_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: password
  defaultAffinityRules:
    enabled: false
  persistence:
    enabled: true
    name: kutuapp-data
    storageClass: openebs-hostpath
    accessModes: ReadWriteOnce
    size: 10Gi
    annotations:
      pv.kubernetes.io/bound-by-controller: 'yes'
  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: data
    name: kutuapp-data
