apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-key-secret
spec:
  encryptedData:
    dns_cloudflare_api_key: AgAS2hgzNAgi8jqteWNePcNg+afjacIiFIPncEUjjqEqbNUvaMsEXw7xpEeyeN5rXNRs012CXTQK4X6Q3N8QY2jDbeNpwkmJ31ZnrAJcXO4m46bapoJGplo6RXNlQphTxk6bOibwTTrO8G7l3GXFtxq1IlJy29djpph6nUC4a5kZ0bV6rRwxCuO9Ecw06441GvSMNXjiEP+K0hJ3diRt1YocJ9Q7QQo9/AQZktHueJl7kTPcDUelDYGBcRUyrzqFY0XKa7B2pwevXK3kOGuhc9N1DXVL5Jvw5xqaTUA7zVPCRnJKe3sWpY58b+POueTynq2yiXhYsNDVa4kCI+9B0CbCcGQ58HM1huQJzC6MHSd2fRnwzcrJj4T9QQsWQiCSuja13xE0kdjBeRK3GO+uNIhREd3jvAjn0rYhre0826SfRQgIM8uqXe9XekSxpsY9rd4mZt6/4Hamzanc4J6+2GMoC4csqwb1t4VipRlDBxeVTMReg1aP0EqrlAbcCHCdW9PAeW0F0SGdFnWYLgpN+Vyx0quD60QKBhSZ35Mxdbd4qS9wH24aDKGk9rg+7AyEzcsNehH9f7ZLbkJzN2q8YfDIiQ/run9nlYRs7Jfohbf9rlobvWOhPsnV5QJW6VBkubiB76L6YUtl12FgboZbmvZOrhL0poOrNxKxdkYWWYY4dtVqZIpLpxq2/CSqqH/CiSl5E7OddNijY1KouCcQStLD18jvlG7HEsVUHe02Ra3GFCS4SQEcUA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-key-secret

