apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-token-secret
spec:
  encryptedData:
    dns_cloudflare_api_token: AgBuEF+qGVwWY04v9arFwo5Vh8htdcdrOyVfOf7BIzC1RYOZr+Dgsx2gkgguEjXU1Q7NVv4HBOmnBR8WX+WAHxX5DSRL8n3uUhoXmxcxmJY8ukvDTvphNlUYLm/EGZA4YAPHfAZIil4zAMm8ozpRpvCNvAZTGuVt9WjJXyFig7wHlO8U9+HjF5d4QgcreYN5s0F3M29evuLVHN/utKj1VRClLg/o14BMZY58POF8s+0KhoWSXFkjGPtxyLzh00gm+j1vAuvo1W6LZCUCBoI28qx3J7IhDdpwJE/U1s5yO5fSQAn0/q9hWmEwwjv8Ykd1gEBu0WBsg5CoizgtztjNivDa77J7YRGmzk6SuQJQm4G0bZDCGWHkY6J4lkP/zurtq/j66s5VJPhwC5+1pfel/AlVXr6fYmfYHeT6LnhX85eR9rib1p+wUZagZ3xJNg7GfuFAg5h7Gs2MJOlSb7q+h+SWoY528pGIPrDJxyXwPt1tV0nYYj2NPiroWOO5eYpdZ0bSdLi0UAybtovXCAxIIaDnE3jNGQbLx1iW0HE5TycX1AVpf757urk9cMT+0e7PxRNdLd5VqgaUa2Kh9LfQBNh2m5PJlEO4e8Yn6aY+XEzNz6tsvQVheAmsdI/Rl2HjBXfeqVm+6njbJbHC5m3VMeN2HaSvwjTQV8ZXRQMtPi+ogL/fR+0M7dgVNTn7WinbW/EboNl7JlTUY7ff8i6BJVPXks3sbZeIKC2JL6qk4KGy3RaqVBVokL8c
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-token-secret

