apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-token-secret
spec:
  encryptedData:
    dns_cloudflare_api_token: AgCo/a2zs48natG90gdUqbpm22YyZx8+iTpG8gs+nj2zMDY1+xjaxa+WZ+woLdl3Ga1JwrEVVDELG7uRIPTX6bT6We4bnqksOnf27ho4yQmYtSww+m451K3PtmjnTcMVQ5NwowB7GfYmAPn/Gud4PNhCc2FoUS0IIusNpirsvff9yQ47odFruL0BKKc9jvcy+lK+5DcC/y+MSlE+o4e7JAbRHC9hQ3x4DRXtRZBm0ktE7yz9oQqbVgTa/8/yjp2sgCfM8/hun+/3Sd4jO0eHbxVuM4MnQpMkG5Jy9V3l56xaxmwTVCqOcupS9GYNOPK8OMQpFGFQk1AO5mNBtXTthoUldNc47IO8vTjqas5aFAeSRUzLNU75jc/qaZNtnlkoxC/t4OtUQzsyWfHXjo4rHjaWwtJZuahKxibeiadmjedOfRfPlLDZiTFV8LFzIxes3ap3AZcV4DstsVoxIQmMDt02ofNaPsX6PQssy2eyNJKJYphp7UEvqo/0UfeuOjllB+M9g3rNr/kBVhAFZJGhxphOIVLdawyLFbNaijOuTdfP6oXAFAinxWi9EWy+Ft//wk5UHfM39lAeMKRsQYkjTIR9Vn8U9kL1T/Bvi2agk66XVyuPGqOLWP4ojvyVK34ZNLHWxo1+/133zd9gT/T13lniR7nxLSRjVhErLx4BqQlXVda+SxxcQHzISSPgQIbWtpAodoHvh3vaI5wvrwtjrohPmGTfIHy54l/7/sJTvhFjVznnOvTCutsj
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-token-secret

