apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-email-secret
spec:
  encryptedData:
    dns_cloudflare_email: AgAJo/0TfXiL9B8GYT/YBMMbYRJFmxrhWF3qEQAnavJwfPWiD0hsjY5rsxqmFrrqoJiB6WSfWQ+pWBJ/8Z99/Bs2bT7m7ZNlD3ib/YBuHSBzGazfxxqq5xx5TuvDGbsz0f99xp+kuvwKGjh5k/tc3Q3A7vBgxL3OaGr26qu+ycHgjL9fxGHBV4ewidc/d2fOimraswzRLdJMrVyJ7r3GwSo4GMeyYBRIzIt38SlRuy+ofNjn5/6KCITSf7lFVou4H6aNDBf40v41diEvRQ1tb3JDN+HmfnfxOmkUQQjacocMUEgHAC6dRtdy6qTprD/XlA4rgz54Y6xogQvXxzsYBiLLLPpuWUwJq5AdKE5bIHz2QFaX0pUpQwku9BVXf16CGJvHFdVimU2nRPCl2ZKu+q02XCb8c4bJbcY3wFhY0WZem6gu8fytx25izZ/iSmwQMVkQHAeJkECqiWonH1sxs8+gDTUI3IG8F3Ups2MH8Kou9jN5NE8yfRHYcyG/Dzagza3pWUF+mfRnwpniVAfjButY8MK7J7X7fJ7Qt1dlOrfPRU1t7Ofw/dF7O+GRymNnpLpZ8EvT+Kb9ydYAxiSf3wQ5zY+yVm1L3CxIPxiipukB1OIrhkTmZCxOCnwkGqII53a9MgVzDLg0xnv6kUXO8AQtN9TZz24nRrGkvr7bkXjywBB8zXzx7PQOK/Mzkq00j5HHphPfIWvljuOp14jLp67oJmZC
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-email-secret

