apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-email-secret
spec:
  encryptedData:
    dns_cloudflare_email: AgACnQGqfl0TLfjOXXqpiUJO/UjV5mP8bjGS/PiiwrcVI00k6i3s8bQtBDeZEBsR24zVEU4Ky2MBspJwFJG0vGvqAMszWJyEoXpevAUYwp13rd9KEELxurZnL0CIbiW88gsYgwYFLA+zX9r7yBzWdRnhnWLLBell/BXuHzPhEPOO+IDTXqc0IyzX1gfl7o89sZxTkZEP6w2+3Mg33xR58gohW7WQUBH9SVaE7rvTGYobf8lkkpvL+9BlUTe1XO8Ikm7tWXnG1o+hSBGTG/4AGV2TeKCQA+u5jP7Iy1wJJA0eMlLBC0MLUBqAR6QfDDbJPzyxfoLRQwsbeJ573gFPckzd0TS3ZmakEghNFnnWP3BWksOhqSfMawOwjJcG22NbnmAvN8+5+B6lmSMiH893TFW194VKGmW3lkXCsM0OgEK7/sIJ/fWHhpbD75tw0MExqAH1OBEIIiA17zumTF7PtvpJrJhDvovHnznWyqOUY7zdKcLPfQYkp/x/yVX8qkSa2LvO9rpX4Hby1VAoWczsk8NGrQbxkqyd9d9R8FvydjdJAmzuve08T7D0ujpOSmpLtULBviK4Bt9EzLh7GLmPNvdt1+N9jBIQfYke7H784rYpkbXCBxiLeYnIz+oooxmvqSvdwSwVz2TzFGj8wl7bDckFKGaAkcZ4x08ZRlgSYDzLxLR1qZ9ooequFxRw4On+lrc+fumuK1KNo4/wH2wrgLc/3vKt
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-email-secret

