apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-token-secret
spec:
  encryptedData:
    dns_cloudflare_api_token: AgDLEvRS5tQ1WlACh3IJ8uXZ3lHycq6JQHLenjOiuVSmjT+8PYVdhavRvqLkA6UpEtm5XUY/1CgVLVbLNscibtu7CWXrgyHoDpHKlkl3xzcaJZYa9S8TeAUj0L3ETe7SzyBOg9eFrBZtZqVQcDC2HHuj05RABY9y2wYHhuLzvUcmCn7J4RwG73kr4YUn13To9UCondnOygicBEZ0IRdfS6llM2VHVDij2X0D5OeXWfS3zzSDCqJrxErachd5jrBuFqGzd4lDII+zTzjF7HH9FtEiSUD1GaBwS+kAQzrtY6aVjd8VImFHuaCrod2EHOEGIBQuyMl+YK69e44YtLWKSBmgDsR3DfU1TkBDW43rPYRB+oLSS6U03tiRtSywZ830Ha7nydAg/flGe7v0CxDU9/uuc4oe/6CnAVYUGhEnd+prR+Jo4AFVcDtxGnFn6dLHGQ0TN4sr9zvKe3Ny9eHFXtApiNA/ev0d80ptlfhmdXMenlmO1oV3Fh4OedGWjrUWYhKtxmDWTYGde9BoqWmZbK2ykvXeoRv4wbC01nvYh/VMkeJh9ouOhiZkiIw8jiVax4iMbItVCDT94zXEHdHYIPM07abdjWHBP2xek7O8q9DgL+UX1u5fWgfF3XcVzp1e+vDkuqsnUXPfdpmKTmw6qgnPy9EOsjOtrhbI6OshyUEHXsDeF7MKj1rhW/zG0Dzzvj+iUN2SN9SFbYetjoqwXkD38Br4WxDwGAsN87erLxb6idfDs0854sdXpg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-token-secret

