apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-key-secret
spec:
  encryptedData:
    dns_cloudflare_api_key: AgAe8lOOE5F0ALHQPneN0SppGUFp56T7AZWvRHhL/3j4oLDhb4HrsCWIizHB/oaTi9f2EtIL2yI9+aJghTwstaxpwWemZo1gHAyPyOFUUKfUwNfOjlB5XYq1OWvW8561XtJU1rIoA6oecIy6sxD+5OGaxRwBoULcsCOYbwrPrkKWrJ7N+91cLzvdogIGgJ/Lp2YzRmS4FEw3tFwLNbLcPDOTbHVodZFbH1YNOiuyvvZVX742CvfSpDDGCrw/dU7PaTJT6WuoyTMJzrAGKkaflSDRFg0Bwiqg6spF3xNl4VlU9a2ROY90zuDDsVwANWwWCJQFlRXGRH7Bh0/XKiihO+TAcpnxpzyi3Kk85bS/lQstshJ3raurBCga2X9SUuj2MF1zP4E/gPpxZK/JQIA6gcUJklxLUDRPfppqhyWAN9kX+TpP59mqLvNxBcu/tKI2JtoTVQf2MMCh1GdDLwpMrXyy34Dk79Or+h2J19aEs4Xi//LMj7hbb3g0fcRm3LxLpD4MTN5PA4lyTcVHqVLrJeMF/jwuhAAyc596qzpjJ3f4N/np3tPG6Zf0Z2NCvxi+h2BOeC7UJwuMX8+6oC+XVWEz0igzLm9IRxoY/2YbSKqZ0v7e10JKXJrs8CQ574UwudcYn+FcA+ZOX6c2fHS4pgJ6JDAcQ/mQZZJjJ7JHRAwy+Z81VV6Ihfj49pUQYJOjJ2LGv0/+Uz9PYD7UuLtWQyzrkCweFS+sMWt/ngpzT4PTM7FXbBtL
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-key-secret

