apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-key-secret
spec:
  encryptedData:
    dns_cloudflare_api_key: AgAgb6WvRFJ1ie8S5dyT1FObfUXhQd7riIZqd4j+pE9O8ziF1JFMiMiQtGvozyd5/UXxtD400YkguHEQEZ4N2yY8tG35tce0wpalPSQIJKFav6KZqW9EitIGk1Il27b6vs45KXBtI0KQZGjI6QtUT0aVLjCiz21rxplYFVFFZrMlN/2HBZITz+BH8K3kji1MMkiLAjmdEOIu28JJalrLf4efKtqR8B0Gmuc8bAdmxorIatBiCqiXZ9criWzwiYC7l2cjqn+8OIMAtiMdz68EEjvUw892wvlmMKVYbQmj+4QEgh5YR/bWIJWi0atd09474b5bStJYRm8Ay64GYf7CHY4P4u7fJzLQaP2gL0XIHtaaw1aGa8+ejR8TKDak68nwaWiJm+SAnS3XUGsSKzXqkY/0DN16Rb+LWRyVPf2TVHgLfO+f1dQq5+AVfpyW8/uGOltcaRXueUMl/TJ1IgRFJj1waJAi1YOKsY0QJfbVHS710EY3qMS35eiy3bat4Cv3XwA9ahRsP8vyHRnuolB4J4DzH5FNxEqLiMBoDlyYPmD+Kh6dQPeLmDDHJtbNGjWQczG80UEBK4nvF1jVi6gm0WaL2EnHGR50mi9BVkJ5SL17+SwtbAn4T/5VrxsiMuE4wK1gX1eYcfpv5Opan6cMNwEzp+UqDzK1BcQFlehz9nO0qcF7b7H7QqrZZRndtgHKdv9yGvZ04THVP12Eqmy+v8UVH2CMbdR2gKgSYHOWrx3LaBicgQFw
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-key-secret

