apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: acme-provider-email-secret
  namespace: traefik
spec:
  encryptedData:
    dns_cloudflare_email: AgCjQZ1oZZK/iTPmNH0ZEvRIwaL9eL65NzXRSMjF9VXvO5EUMiANkgERoVATcMYH3OYyWakYMXXwaCPhER7BSxzCz/aUmHxI/bEwBlhC+VTYZ3PXpaZQuLbVVQ/gTuaAgsR4Nxmpm0D6H+pWTwS+7+DPTmq6EwLtle6E1C6E44fGACRo+2WyeqvQE3iAUgaO0UU9CrXqcugj57x8Wws2Kujl0cUwMvIfu2rZblFpiAXLdT7TXpkt9avhuI9giGHwEt3Qfm2IQ9U4smuZy2ieOPfU9Kzh6fxAKJ/AW0stjHOMhk4klsTcE0fVVfg3anIJFgdp1uc8Q01QZgZ2+rX5RJvCk3HgsvvK+DF1uXm/8c4+ayAi69kZ94VMJdR5r/TDTWKNWHZgxuBz4mFR3J5zFdvAhSwY7sVXCS9jDhJaCilka0JaoNXXsPJXYgc8TVE+wnLwleNe695SqUrxa4hih+NC62x+eynM8moOvFExYRhoGoYqI3DKM641s460l9iNn0POoZTtgqYaU3zhOKcPNrcTZ6RLmMZ4+zYPdV6bfUo8L+jSlIdZdRCowrT1w9Ib2GrzIX3z0BkjEDP30ur3RqSfQ1+xX8XXD/f6AUenf011qAUhnNeed71zdYPfzAUaxcXQ9mall6BViWghdNIhXrzGKW8YjP1MLRWtT9AHZeHjby8ZKqSQlBEKOyYOSsqNgE5AfuuEmanQJ7g0LJ2HoiqLVCMN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: acme-provider-email-secret
      namespace: traefik

