apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-key-secret
spec:
  encryptedData:
    dns_cloudflare_api_key: AgCyEorAUGJN2IMPG9cbAjCWe0juZ7ADOi8Ix960PJFYIWNsiYCTY99YK2s6mk4No+tdLsAFKf1oWGgJgoyHVb+DrQxcHpsp8wwwXpqXSnXdJ72hBB2ZgoDBeHqqgu9/YsBcIfH5Rje0wOweQ3VeeRxjxOjMRujrgLeGK9yJX5Aj02i9cKEC40Ju7YRYXEsOSrHeb+PrrdzkB05ejFNjnQ/hfmXFxUECojL3hDI0oIyNRwzmbZKp4Ndsiyx+gOXb7Kj6obTY99nY02ZxYxzAINvRZiB5/8BXiVOtovyQUy0rU8eAs3fksGrDtI2zFBoSBkm68ul0yvW9N96W+ROr4yhN+VAou2WFer0CqYU/UH+GvKQgT/27B6DFPuhl47M2i6tdiH9egU8wC4rzdEO2JizmqayMHw4AlGr9pDluwpuSomhO2NFxSoL8MKIb+BYqhbpbRvaUNerNqz1vN4RrUCXcBU+232A9I6PQO03mLw0pz/onaBpCJSU+YeasysBnCps7ObXFZEJLiaDWYOpu3z5io8+wfOZevLlmEeBfqsYxJH5IYf0J2K4Nz4lzutYRtHZisRyJ1eoqEjGtcI+idHX6qvlVMd/a3vnUC7kXLjMihMa2fxhfqMO+GqIxqChg005h2WcED076pXG4ZaBJULKIxU303bWmpxL4aPAomFyNChRwq7pMgsNb+75pKsbbX9JVngcBhZonCMn3qoFaFMmhRK2601NvksOYv/bDVq74wO/7hZWu
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-key-secret

