apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-email-secret
spec:
  encryptedData:
    dns_cloudflare_email: AgCumxL3lGqzQiHKAKQsMihqH7XnGMnnX3ufbPgKcFjhgEq/PG8E6q6WQoUDVACg0ozOnXKXO6ljpDS9XOBjf5/WZkL390/7i/g5RzzjoE4eEBfja6vWgRedhSt5wzwNlObn1S694AN0QVm9mWGgMeAovlEOJkapcsm11fm0hMKV2gGUR32YmxuZR4Y4e3t9GTLhg9G06d0NdlnImpZtWJBIiG/1USNnryX8C2AnZ2sQ/kOkN1drWtmZhXtluVB3z2dG3dsmufOuFjBQOKUMf/3fjKvTBCsLs/Hrs1B3SCJfwKuzdP1TRNtOchhcq+T+NzyJR/7RABnZSrVLV0IdhOZvwYDckhjoJiRKmAEaJ6NtuqLzbaJtQxg28asnfzqIvlYogchxhwxOgHUNhOxYdrZ2ehTL+xRe2gGBdQQ/9lEVqkQjU6ngeEVPBImx5h7iwe3Aj426l+FxzdS4Dkcw++zE3pbermtGQhcYXPSuEOUYdmDADDypUezGjjKBMAMl3/PFs1UCKtLlk8sH05aFQCXV0aoCESYrWsks1r8pcY77tiam8EybsyF4V/WJbKS0QeeZJkauZcF38uJQujVenEtpEdEheQLGebkMYw7XC0Ilc7Y8GKUvFpY/LJQILJl0lO64kqpgReQwNiPBnr8CFvWcexeQHfa79nURyCZKTpq8GzCqwbkw4HXqeUgB+OxWTDcCdUR931RRI+7x7mdWgck4Qi+3
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-email-secret

