apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acme-provider-api-token-secret
spec:
  encryptedData:
    dns_cloudflare_api_token: AgCdFZ6u9N8zkOBKUlUaw5MhpYaiFjIGxNOwmruqyZ0isTJrocrC1ptvieL8y/y05yn00eWWqmVueJl/rYPho1sn8/4X++YZWgHbVck0lsFO7M+7qJ28U+6JIJAcUIuuP+6oHrots5tAQqcGbDK6JBFAtZeajlp8GBX6W8Tx6gKFA6IvlXwokSx+U2aiKNywh63qms9sMVHso7waVw2Ir9jxzyjEJfpogD5G9i7nsGjZqRxi7lZLbD9W3BgVD9dbEWbK9H/6kvjwdjk1sbNUVEbxGTwhDuGVAsbE0WxWoeKTk69ITDk2sSnK3q+/Lws1d5UPx1HiYNTJVkRx72g3IwOMJAUtuuCbVC3RxEUZBMAha9gq97QnvhMyp1gRUVw89/XbMZ6oTgpVJYBsQychnqBol5b52016uFbE35mOXr6HY6Es6LGhA7jY3FNdOUIodLniN9HzVY9plHdPU4Kn8S3lH5qEjrT9YwFekKSglZbt9xaRbtYaCbS3RajFt7Y+Ua5odBSxADywAvsvlKYWRDWn+ImpdVqhB66JpLOHtgOcbtHlfBGL20ZEjDuGL2/xM1U0PjVFXr2nCapndzkbwSLilQ0L5unsyPqraIQtIEMNnJU0czP7D6J4zB5bgYNwNf2IUw0Ywid8bUPkPT6WdcBiHPb8eNrKlOb904xK72Y5GEfa46GWLi/qfg9nOnffXmmRs3lLE5mPPQ+84cNA2XWhRbaAAjEB1SC70n7ZJ+E44cg4io+NWXGv
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acme-provider-api-token-secret

