apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: rook-ceph
    namespace: rook-ceph

spec:
    destination:
        namespace: rook-ceph
        server: https://kubernetes.default.svc
    project: default
    source:
        path: rook-ceph
        targetRevision: HEAD
        helm:
            valueFiles:
                - values.yaml
        repoURL: https://github.com/luechtdiode/mk8-argo.git
    syncPolicy:
        automated:
            prune: true
        syncOptions:
          - CreateNamespace=true

