argo-cd:
  installCRDs: false
  global:
    image:
      tag: v2.3.2
  dex:
    # name: dex-server
    envFrom:
      - secretRef:
          name: argocd-dex-github-secret
  server:
    rbacConfig:
      policy.csv: |
        g, niiku, role:readonly
        g, luechtdiode, role:admin
      policy.default: ''
      scopes: '[preferred_username, groups, email]'
    config:
      admin.enabled: 'false'
      statusbadge.enabled: 'true'
      dex.config: |
        connectors:
          # GitHub
          - type: github
            id: github
            name: GitHub
            config:
              clientID: Iv1.696e329182673296
              clientSecret: $GITHUB_CLIENT_SECRET
      resource.customizations: |
        bitnami.com/SealedSecret:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            hs.message = "Controller doesn't report resource status"
            return hs  
      url: 'https://argo.interpolar.ch'

  ## Argo Configs
  configs:
    repositories:
      luechtiode-devops: 
        name: mk8-argo 
        type: git
        url: https://github.com/luechtdiode/mk8-argo.git
      helm-public-charts-repo:  
        name: stable
        type: helm
        url: https://charts.helm.sh/stable
      baloise-dev-repo:  
        name: incubator-library
        type: helm
        url: https://registry.baloise.dev/chartrepo/library
      bitnami-sealed-secrets-repo:
        name: sealed-secrets
        type: helm
        url: https://bitnami-labs.github.io/sealed-secrets 
      kube-dashboard:
        name: kubernetes-dashboard
        type: helm
        url: https://kubernetes.github.io/dashboard/
      rook-release-repo:  
        name: rook-release
        type: helm
        url: https://charts.rook.io/release
      openebes-repo:  
        name: openebs-zfslocalpv
        type: helm
        url: https://openebs.github.io/zfs-localpv
      vmware-tanzu-repo:
        name: vmware-tanzu
        type: helm
        url: https://vmware-tanzu.github.io/helm-charts
      prometheus-community:
        name: prometheus-community
        type: helm
        url: https://prometheus-community.github.io/helm-charts
