argo-cd:
  installCRDs: false

  dex:
    name: argocd-dex-server
    env:
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: dex-argo-github-secret
            key: dex.github.clientsecret
  server:
    rbacConfig:
      policy.csv: |
        g, niiku, role:readonly
        g, luechtdiode, role:admin
      policy.default: ''
      scopes: '[preferred_username, groups, email]'
    config:
      admin.enabled: 'false'
      statusbadge.enabled: 'true'
      dex.config: |
        connectors:
          # GitHub
          - type: github
            id: github
            name: GitHub
            config:
              clientID: Iv1.696e329182673296
              clientSecret: $GITHUB_CLIENT_SECRET
      resource.customizations: |
        bitnami.com/SealedSecret:
          health.lua: |
            hs = {}
            hs.status = "Healthy"
            hs.message = "Controller doesn't report resource status"
            return hs  
      url: 'https://argo.interpolar.ch:8443'

  ## Argo Configs
  configs:
    repositories: |
      - type: git
        url: https://github.com/luechtdiode/mk8-argo.git
      - name: stable
        type: helm
        url: https://charts.helm.sh/stable
      - name: incubator-library
        type: helm
        url: https://registry.baloise.dev/chartrepo/library
      - name: rook-release
        type: helm
        url: https://charts.rook.io/release
      - name: openebs-zfslocalpv
        type: helm
        url: https://openebs.github.io/zfs-localpv