apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kutu-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
  volumeMode: Filesystem