apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
allowVolumeExpansion: true  
parameters:
  shared: "yes"
  thinprovision: "no"
  recordsize: "4k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: "zfspv-pool/openebs"
provisioner: zfs.csi.openebs.io