apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: pg-admin
spec:
  encryptedData:
    PGADMIN_DEFAULT_EMAIL: AgCIPh0kJn2ypPfEOIWD6IrNDdSGpUhN9CbTLUyL7w3oyFZsQnVdM5wc7vqAIKecnZx5saCjfWzhZNbEwgDlHuevxueLbLlKh3mSy56joi9CmtotiXPZbCqMADAWuNMlY4p6fI/+3SUUXbQN6MQhR4CHgX3KehZKEEBlSAbu8fmBPRtJbt6Ip7t++E/D4MQ4jhPYeUB44DP+6Dj82RPzh0UCPc+ESflyAPOUW3BgvuP4tnnCsQF3CWakX7DM0qR3N9nFd12O2WhBTEB5WVVFSm01lH3dmllFR85yfUQEX9lxjUvwBtKH1zw03KBqUHgWkvU7yrZzC2pyguUgsnTPdguWmqO8CJfLoK1AwQqWEauxNFqQ7IRBa9vitnw6qfaPkwb0ZkScuz0d4LOTAvtyWnygWn2lyEb1/STrbA1tYS8as2BoKdRTqenjZDaaKe91IhxmiZd7zaPzgkKrYNXtb+SaH4unidlt7kd+NcLmlOT7lvnuEThb3KWMg2baJiD//p8ywIBttrH+7Q1S8GS3WiKE2mb6KMj62AYaBr2P2zAkbIEZyPgWKo1T+FutbiJl8676ZTkSbiq4NGxNzOUfvagRREesjWsXR2KI6ZGDz3I3by9Vn88pkrGzvw07zB8Rb03HoNqtueFzgIENJ405iI5FgSJI8c8gFKBa3e2fmsXgWRQAcaTjDkCecveCOaYUEMZJsL5oJv/GqNGuS5GHFjYlV9olP5JqkmlA
    PGADMIN_DEFAULT_PASSWORD: AgBdWQ+MPxmwDDhgETzYv0cN4lpH7bfw58ZJX3KqzdaavmvojReKuCF3X3Q/S6PWgyx1r47JKZTsp2m75ouBmMDGmQ0Va9yvq9qUKq+olJ2n+3UMbZFuxXL2P10mpr03B2I3IBN/MHcM03gXcnwrFzZhSIKnyssYstBChAiTlnvu0DJRl8qiR157jE/+dTRH1MQ3WeMGaiez6L+dVr3uqLUcvtlVY3nL+srTV6VG45XbU2YefM2STIpy3rbfxrdDn09xdCmzK3/kSZrrUDfMAmqvrerWXA3dWg66zRqSWvZxFao7FailJnk6bsttIFjvC95pupVQRiz0oVQ4WtpRn05jhlLx350fYJqEeLBAVG85Wla7XfHpWN0/o08MA66huIfQ8xZ/MDQ6X0zwcLLtLrHl87FlsGpl2wsehtLQP+/sdvbQLKbHUiPHxJhq3yR7kdFZY6aQ6en2bDORZP+g36xCgNTe3515TmBFyttU5RpbKLs0XIuhBlwAKv5Qa5oKQ2ql4dPSaI8s1bcotPkSL/GAxlzez4qDfW6vpy2s+MAjXXyD5+tG+U6qWa5Fqj6o5Kzce/p3U4c5T5xoC7vXbgziTrB4rpLF+g84s6A/5jkz00NKwwzlSsJDodzZeLKeuSNb+4GsCVFZ3x/y/UEV+nu9OKmsy+T1AF8cFwd2v00eqB8K8LYE6LzHa6WuYq93vFxIefKv3Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pgadmin-secret
      namespace: pg-admin

