routes:
  - name: mbq
    domains:
       - domain: mbq.sharevic.net
    dns_resolver: "cf-production"
    port: 5858
    portSecure: 5858

mbq:
  replicaCount: 1
  image:
    repository: luechtdiode/mobile-queue
    tag: master-3f6ce2a
  additionalContainers:
    - name: mbq-waf
      image: luechtdiode/nginx-naxsi:v1.0.0
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-cm
  network:
    waf:
      containerPort: 80
      servicePort: 5858
    http:
      containerPort: 8080
      servicePort: 5757
  service:
    type: NodePort
  resources:
    requests:
      cpu: 0.50
      memory: 1.5Gi
    limits:
      cpu: 1.00
      memory: 2.0Gi
  defaultAffinityRules:
    enabled: false
