apiVersion: v2
version: 2.2.7
name: kutuapp-test
dependencies:
  - name: generic-chart
    version: 2.1.0
    repository: https://registry.baloise.dev/chartrepo/library
    alias: kutuapp
  - name: generic-chart
    version: 2.1.0
    repository: https://registry.baloise.dev/chartrepo/library
    alias: kutuapp-waf
