routes:
  - name: kutuapp
    domain: kutuapp-test.interpolar.ch
    dns_resolver: "cf-production"
    port: 5757
    portSecure: 5757

kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: master-eb3a6a3
  network:
    http:
      servicePort: 5757
      # ingress:
      #  host: competition.sharevic.net
  service:
    type: NodePort
  resources:
    requests:
      cpu: 2.00
      memory: 2Gi
    limits:
      memory: 2Gi
  env:
    - name: X_KUTU_SECRET
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: kutusecret
    - name: X_DB_CONFIG_NAME
      value: kutudb_pg
    - name: X_POSTGRES_HOST
      value: postgres
    - name: X_POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: user      
    - name: X_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: password
  persistence:
    enabled: true
    name: kutuapp-data
    storageClass: microk8s-hostpath
    accessModes: ReadWriteMany
    size: 1Gi
    annotations:
      pv.kubernetes.io/bound-by-controller: 'yes'
      volume.beta.kubernetes.io/storage-provisioner: microk8s.io/hostpath      
  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: appdataroot
    name: kutuapp-data
  - mountPath: /home/kutuapp/data
    subPath: data
    name: kutuapp-data
  - mountPath: /home/kutuapp/db
    subPath: db
    name: kutuapp-data

adminer:
  replicaCount: 1
  image:
    repository: adminer
    tag: 4
  network:
    http:
      containerPort: 8080
      servicePort: 2222
  service:
    type: NodePort
  resources:
    requests:
      cpu: 0.5
      memory: 800Mi
  
