{{ range .Values.routes }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-passthrough-{{ .name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ trimPrefix "https://" .domain }}`)
      kind: Rule
      priority: 5 
      services:
      - kind: Service
        {{- if .host }}
        name: app-passthrough-{{ .name }}
        {{- end}}
        {{- if not .host }}
        name: {{ .name }}
        {{- end }}
        port: {{ .portSecure }}
      middlewares:
        - name: secure
          namespace: traefik
      {{- if .host }}
      - name: app-passthrough-{{ .name }}-header
      {{- end }}
      tls:
        certResolver: {{ .dns_resolver }}
{{ end }}

