apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    postgresql-password: AgCsAa3/tcdo3J7/qW325Lkh/XThSMlraam19pUP+iOI+MekAqVk/WqiVwNcN0n4QABKah5au51dObaHvT6SX1uxCOm7O//fBXHbDBEUZqlIzpZxKdfRlDoKNpMQiP5gVgjlfC9rVJvosxA/qZupYOHOPgcB5sQtku636MxHHnCiz9UXtbtWuD0jEN8ejym+qQcMR2/Pgt/1r3hdpDKZVwp8a2F6diOBAwtQwZCeLYUkrHmMZKalf73twHkdK3Z/rX2MIyCfvQPm0yIWISjWKZx3svHHu6h64nzLlxZAmeL10LuLGE9FB9Ug+28QqH6Tp04Kscf/rv4VlXMjFcY7c5E0NPAk9Cx3k8SLg1D6gHXkNCkuc9ViNcvWGqQ9BjomAz+VJ0S1D8kJA7G5W3FrZd84U18eVwc/lWfiS0S9NnBtHB69z76VV7BuhtsdPhKjXHzE1gGCi1Y8uEOuSfGDOJFaT9F9nWGsX7ASdioK3ymMFaD1MYGf49LJyMXd+iSFKoaFJKq4ql6bz4fcMXis5JrtCDSbYBG9ISkX95lIHWHzTb4JKI1HEhH0nWjEzkM0Z/tIJIxlhLG4gsJcDUMAHyYSWpq1loadUz6vzVPbjWtUjC7c1Gb+u997Q0HDOVXxWYLTK1U0uj1Xk6c130JbyHUp4Qqjw9ipl0qy40mLqkEo59kodLsLGB8CE/FDAUvy15LN6VxJg2Y9Zg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-db-secret
      namespace: keycloak

