apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
    component: postgres
  name: db
  namespace: keycloak
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: keycloak
    component: postgres